name: Foodtour
description: "Foodtour"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_riverpod: ^2.5.1

  get_it: 7.7.0

  # Remote API
  dio: ^5.3.2
  riverpod_annotation: ^2.3.5
  get: ^4.6.5
  http: ^1.3.0

  flutter_launcher_icons: ^0.9.2
  flutter_fortune_wheel: ^1.3.0
  confetti: ^0.7.0

  # Log data
  logger: 2.3.0

  # Responsive UI
  flutter_screenutil: 5.9.3

  # Firebase
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  firebase_remote_config: ^5.1.3
  cloud_firestore: ^5.6.2
  firebase_dynamic_links:

  # Auth
  google_sign_in: ^6.2.1
  sign_in_with_apple: 6.1.4 #6.1.4 5.0.0
  local_auth: ^2.3.0
  facebook_app_events: ^0.19.3
  # flutter_facebook_auth: 6.0.1

  # UI
  flutter_svg: 2.0.10+1
  smooth_page_indicator: ^1.1.0
  flutter_switch: ^0.3.2
  fluttertoast: ^8.2.8
  flutter_card_swiper: 6.1.0
  salomon_bottom_bar: ^3.3.2
  shimmer: ^3.0.0
  loading_animation_widget: 1.2.1
  flutter_slidable: 3.1.0
  dotted_border: 2.1.0
  gap: 3.0.1
  el_tooltip: 2.0.0
  zoom_tap_animation: 1.1.0
  qr_flutter: ^4.1.0
  expansion_tile_group: ^2.1.0
  carousel_slider: ^5.0.0
  lottie: ^3.3.0
  custom_refresh_indicator: ^4.0.1

  #form
  table_calendar: 3.1.2
  pin_code_fields: 8.0.1
  dropdown_button2: 2.3.9
  video_player: ^2.9.2
  chewie: ^1.8.5
  calendar_date_picker2: ^2.0.0

  # Helper
  flutter_local_notifications: 19.0.0-dev.7 #17.2.2
  image_picker: 1.1.2
  share_plus: 10.1.3
  permission_handler: 11.3.1
  app_settings: 5.1.1
  #flutter_native_splash: 2.4.4
  jwt_decoder: 2.0.1
  image_cropper: 8.1.0 #5.0.0
  android_intent_plus: 5.2.1
  device_info_plus: ^9.1.2

  # Utils
  intl: 0.19.0
  intl_utils: 2.8.7
  scroll_to_index: 3.0.1
  collection: 1.19.1
  url_launcher: 6.3.1
  in_app_review: 2.0.10
  upgrader: 11.3.1
  package_info_plus: 8.1.2
  # full_screen_back_gesture: 0.0.2
  # cache network image
  cached_network_image: 3.4.1
  flutter_cache_manager: 3.4.1
  my_back_gesture:
    git: https://github.com/congdoan99tm/my_back_gesture.git
  app_links: 6.3.3
  android_play_install_referrer: ^0.4.0
  go_router: 14.6.2
  flutter_keyboard_visibility:
  flutter_new_badger: ^1.1.1

  # Local Storage
  # flutter_secure_storage: 9.0.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  path_provider: ^2.0.11

  #HTML and web
  # flutter_html: 3.0.0-beta.2
  webview_flutter: ^4.10.0
  webview_flutter_wkwebview: 3.16.3
  flutter_widget_from_html: ^0.15.3
  # flutter_inappwebview: ^6.0.0
  # file: 7.0.0
  flutter_map: ^8.1.1
  flutter_map_tile_caching: ^10.1.1
  latlong2: ^0.9.1
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
     - asset/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
