// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpFjmYQ_fcyAwlHTWUI13BN',
    appId: '1:190281708002:android:125930e3d5349f46d5c9bb',
    messagingSenderId: '190281708002',
    projectId: 'foodtour-9112d',
    storageBucket: 'foodtour-9112d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDNP8WHrLR0DJUJ5iGZh4VmppQwKWT6QQ',
    appId: '1:190281708002:ios:2827c8a9e0d87092d5c9bb',
    messagingSenderId: '190281708002',
    projectId: 'foodtour-9112d',
    storageBucket: 'foodtour-9112d.firebasestorage.app',
    androidClientId: '271753063437-5onecijnufr9ukcmm6n9sq6c1uqcdj0j.apps.googleusercontent.com',
    iosClientId: '271753063437-o6c1k6ut5rtik7hlciodh4lq27m9ctli.apps.googleusercontent.com',
    iosBundleId: 'com.dinos.foodtour',
  );

}